feat: 職歴を追加・表示出来るように
yoseei/initial_project pull request #7
Opened 2022-02-24 06:52 UTC by yoseei

![Screenshot 2022-02-24 15 51 01](https://user-images.githubusercontent.com/71750637/155473220-156af3d2-4b21-4412-9604-495ee6daad08.png)

2022-02-25 08:53 UTC, nozomi-iida requested changes
頑張っていっぱいコメント書きました!笑

2022-02-25 08:53 UTC, nozomi-iida commented on src/components/molecules/TextareaGroup/index.tsx
> +import React, { VFC } from "react";
inputGroupでchildrenを受け取れるようにして、inputとtextarea任意にできたほうが良いと思います
それかinputGroupと見た目かなり違いますか?

2022-02-25 08:53 UTC, nozomi-iida commented on src/components/molecules/TextareaGroup/index.tsx
> +      <textarea name="" id="" className={styles.textArea}></textarea>
name="" id="" 
空文字だったら必要ないです

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/History/HistoryRow/index.tsx
> +import "antd/dist/antd.css";
App.tsxに
`import "antd/dist/antd.css";`
を記入すればいちいちimportしなくて良くなります

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/History/index.tsx
>    historyType: "職歴" | "学歴";
このコンポーネントで学歴を受け取ることもできるんですか？
propsを見る限りworkhisotryしか表示できない気がするのですが。。

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/WorkHistoryEditModal/index.tsx
> +import React, { VFC } from "react";
このコンポーネントって使ってますか？

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/WorkHistoryModal/index.tsx
> +  cancel: any;
anyダメです

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/index.tsx
> +          {/*/>*/}
必要ない場合は消してほしいです

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/index.tsx
> +            visible={isCreateWorkHistoryModal}
👍

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/SignInPage/index.tsx
> +import Input from "components/molecules/InputGroup";
inputはmoleculesではないですね
ちなみに、atomsとmoleculesって分かりますか？？

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/index.tsx
> +  const [mappedWorkHistory, setMappedWorkHistory] = useState<WorkHistoryData>();
mappedWorkHistoryってなんですか？
名前だけみるとなにかわからないので名前が分かりにくい気がします

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/index.tsx
> +  const [workHistoryData, setWorkHistoryData] = useState<WorkHistoryData[] | undefined>();
初期値なにも設定しなければundefinedなくて大丈夫です

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/index.tsx
> +    const newWorkHistories = workHistoryData?.map((workHistory) => {
if (!newWorkHistories) return;
やるなら、
if (!workHistoryData) return;
こっちでやるのが正しいです

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/WorkHistoryModal/index.tsx
> +                    text=""
空文字だったらいらない気がします

2022-02-25 08:53 UTC, nozomi-iida commented on src/pages/MyPage/WorkHistoryModal/index.tsx
> +              <InputGroup
エラー文でるようにしてほしいです

2022-02-25 12:29 UTC, yoseei commented on src/pages/MyPage/WorkHistoryEditModal/index.tsx
> +import React, { VFC } from "react";
使ってなかったので削除します！

2022-02-25 12:30 UTC, yoseei commented on src/pages/MyPage/History/index.tsx
>    historyType: "職歴" | "学歴";
ここも使わなくなったので削除します！

2022-02-28 01:50 UTC, nozomi-iida requested changes
コメント確認お願いします！

あと、wipのコミットまとめてもらったり、なにか修正が終わったらコミットするとかにしてもらえると修正箇所のレビュー見やすいのでありがたいです！

2022-02-28 01:50 UTC, nozomi-iida commented on src/pages/MyPage/WorkHistoryModal/index.tsx
> +  cancel: any;
こちら修正をお願いします！

2022-02-28 01:50 UTC, nozomi-iida commented on src/pages/MyPage/index.tsx
> +    });
`if (!workHistoryData) return;`

105行目に書いてほしいです
理由はworkHistoryDataがなければnewWorkHistoriesも定義する必要がないからです

2022-02-28 01:50 UTC, nozomi-iida commented on src/pages/SignInPage/index.tsx
> +import Input from "components/molecules/InputGroup";
> ちなみに、atomsとmoleculesって分かりますか？？

これどうですか？

2022-02-28 03:41 UTC, yoseei commented on src/pages/SignInPage/index.tsx
> +import Input from "components/molecules/InputGroup";
ここの例でいうと、`<input>`タグだけがあるようなコンポーネントならatomsで、
```
<div>
   <p></p>
  <input/>
<div>
```
↑のように複数の要素があるコンポーネントならmoleculesという認識です！

2022-02-28 04:21 UTC, nozomi-iida requested changes
コメント確認お願いします！

2022-02-28 04:21 UTC, nozomi-iida commented on src/pages/MyPage/index.tsx
> +    if (!workHistoryData) return;
105行目に書いたのでいらないです
ここらへんの指摘の意味って理解できましたか？

2022-02-28 04:21 UTC, nozomi-iida commented on src/pages/SignUpPage/index.tsx
> +import Input from "components/molecules/InputGroup";
InputGroupにしてほしいです！

2022-02-28 04:26 UTC, merged